threshParam:
  thresh_block: 0.5
  thresh_opened_block: 0.606
  thresh_num: 0.78
  thresh_lose: 0.4
  thresh_IoU_block: 0.3
  thresh_IoU_opened_block: 0.2
  thresh_IoU_num: 0.35
  thresh_IoU_lose: 0.35
monitor:
  top: 464
  left: 1622
  width: 511
  height: 511
templatePath:
    folder: "temp"
    files:
      - type: "block"
        file: "block.png"
        value: -1
      - type: "opened_block"
        file: "opened_block.png"
        value: 0
      - type: "num1"
        file: "num1.png"
        value: 1
      - type: "num2"
        file: "num2.png"
        value: 2
      - type: "num3"
        file: "num3.png"
        value: 3
      - type: "num4"
        file: "num4.png"
        value: 4
      - type: "lose"
        file: "lose.png"
        value: 999

